name: xdem-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - proj>=7.2
  - geopandas>=0.10.0
  - fiona
  - shapely
  - numba
  - numpy
  - matplotlib
  - opencv
  - openh264
  - pyproj>=3.4
  - rasterio>=1.3
  - scipy
  - tqdm
  - scikit-image
  - scikit-gstat>=0.6.8
  - pytransform3d
  - geoutils==0.0.11

  # Development-specific
  - pip
  - sphinx-book-theme
  - autovizwidget
  - graphviz
  - pytest
  - pytest-xdist
  - sphinx
  - myst-nb
  - numpydoc
  - sphinxcontrib-programoutput
  - flake8
  - sphinx-design
  - pylint
  - sphinx-autodoc-typehints
  - sphinx-gallery
  - pyyaml
<<<<<<< HEAD
=======
#  - richdem
>>>>>>> 933cb7850a144dea0097bef3b78be2be335b3cee

  - pip:
    - noisyopt
    - richdem
    - -e ./
#     - git+https://github.com/GlacioHack/GeoUtils.git
